services:
  - type: web
    name: checklist-backend
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: client/dist
